ALTER TABLE "Store"
ADD COLUMN "themePrimary" TEXT NOT NULL DEFAULT '#d79771',
ADD COLUMN "themePrimaryStrong" TEXT NOT NULL DEFAULT '#734939',
ADD COLUMN "themeAccent" TEXT NOT NULL DEFAULT '#f7b239',
ADD COLUMN "themeBackground" TEXT NOT NULL DEFAULT '#fff6e8',
ADD COLUMN "themeSoft" TEXT NOT NULL DEFAULT '#fff0da';
